### ISSUE TITLE
Numeric limits header

### ISSUE THREAD

**Issue by niliopoulos** [michele-segata/mpclib#1]
gcc version 7.0.1 complains about std::numeric_limits in file src/MPCProblem.cc. 
Please add `#include <limit>` at the beginning of the file.

**Comment by michele-segata** [comment]
Hi,
thanks for letting me notice. I had fixed this some time ago but didn't push the fix. The fix is available [here](https://github.com/michele-segata/mpclib/commit/9202fed39be6681d595e41ae829de6af5323cf66).
With the push, there are some new features as well. Be aware that they are not yet described in the README.

**Comment by niliopoulos** [comment]
Great!
Do you expect to have a trajectory following capability any time soon?

**Comment by michele-segata** [comment]
Is [this](https://github.com/michele-segata/mpclib/commit/d28a1f9a57e0a19ba67356d13b5c3097d5e76af5) what you are searching for? :smile:

**Comment by niliopoulos** [comment]
Definitely looks like it! Will try it out.
